services:
  seerr:
    image: ghcr.io/seerr-team/seerr:${SEERR_VERSION}
    init: true
    container_name: seerr
    restart: unless-stopped
    env_file:
      - ../../.env
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      LOG_LEVEL: debug
    volumes:
      - ./config:/app/config
    expose:
      - "5055" # Web UI (proxied via Nginx)
    networks:
      - proxy-network
   # healthcheck:
    #  test: ["CMD", "curl", "-f", "http://localhost:5055/api/v1/status"]
     # interval: 30s
     # timeout: 10s
     # retries: 3
     # start_period: 30s
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    labels:
      - "com.docker.compose.project=seerr"
      - "com.docker.compose.service=seerr"

networks:
  proxy-network:
    external: true
